image: golang:1.11

stages:
  - test

variables:
  REPO_NAME: gitlab.com/visig/pager

before_script:
  - mkdir -p $GOPATH/src/$REPO_NAME
  - cp -Trv $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go get -t ./...

test-job:
  stage: test
  script:
    - go test ./...
